name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependecies
        run: npm install
      - name: check code style
        run: npx prettier ./src/ --check
      - name: Build docker image
        run: docker build -t ghcr.io/spp4tfv/2711/src:latest ./
  build:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: send telegram message on push
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.ID }}
          token: ${{ secrets.TOKEN }}
          message: |
            Переделывай
      - name: Send Telegram message with media on push
        if: success()
        uses: appleboy/telegram-action@master
        with:
         to: ${{ secrets.ID }}
         token: ${{ secrets.TOKEN }}
         message: "Красава"
          
