name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Check code style
        run: npx prettier ./src/ --check
      - name: Build Docker image
        run: docker build -t ghcr.io/spp4tfv/2711/src:latest ./src

  build:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Send Telegram message on failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.ID }}
          token: ${{ secrets.TOKEN }}
          message: |
            Переделывай
      - name: Send Telegram message on success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.ID }}
          token: ${{ secrets.TOKEN }}
          message: "Красава"
